####服务注册地址
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8100/eureka/
####api网关端口号
#server:
#  port: 80
####网关名称
#spring:
#  application:
#    name: service-zuul
#  cloud:
#    config:
#      ####读取后缀
#      profile: dev
#      ####读取config-server注册地址
#      discovery:
#        service-id: config-server
#        enabled: true
#
####默认服务读取eureka注册服务列表 默认间隔30秒
#### 配置网关反向代理
##zuul:
##  routes:
##    api-a:
##      ### 以 /api-member/访问转发到会员服务
##      path: /api-member/**
##      serviceId: member
##    api-b:
##      ### 以 /api-order/访问转发到订单服务
##      path: /api-order/**
##      serviceId: order
####开启所有监控中心接口
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
spring:
  application:
    ####注册中心应用名称
    name: service-zuul
  cloud:
    config:
      ####读取后缀
      profile: dev
      ####读取config-server注册地址
      discovery:
        service-id: config-server
        enabled: true
#####    eureka服务注册地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
server:
  port: 80

### 开启所有监控点
management:
  endpoints:
    web:
      exposure:
        include: "*"

